---
# This playbook contains common plays that will be run on all nodes.

- name: Hostname | Update the hostname (pt. 1) - hostname cmd
  hostname:
    name: "{% if hostname_hostname is defined %}{{ hostname_hostname }}{% else %}{{ hostname_hostname_short }}{% endif %}"
  become: yes

- name: Hostname | Update the hostname (pt. 2) - (/etc/hostname)
  copy:
    content: "{% if hostname_hostname is defined %}{{ hostname_hostname }}{% else %}{{ hostname_hostname_short }}{% endif %}"
#    template: src=hostname.j2    
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
  become: yes
  
- name: Hostname | Update the hostname (pt. 3) - (/etc/hosts)
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1"
#    line: "127.0.0.1{{'\t'}}localhost{{'\t'}}{{ inventory_hostname }}{% if hostname_hostname is defined %}{{'\t'}}{{ hostname_hostname }}{% else %}{% if inventory_hostname != hostname_hostname_short %}{{'\t'}}{{ hostname_hostname_short }}{% endif %}{% endif %}"
    line: "127.0.0.1{{'\t'}}localhost{{'\t'}}{% if hostname_hostname is defined %}{{'\t'}}{{ hostname_hostname }}{% else %}{% if inventory_hostname != hostname_hostname_short %}{{'\t'}}{{ hostname_hostname_short }}{% endif %}{% endif %}"
    state: present
  become: yes
  
- name: Hostname | Update the hostname (pt. 4) - (/etc/hosts)
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.1.1"
#    line: "127.0.0.1{{'\t'}}localhost{{'\t'}}{{ inventory_hostname }}{% if hostname_hostname is defined %}{{'\t'}}{{ hostname_hostname }}{% else %}{% if inventory_hostname != hostname_hostname_short %}{{'\t'}}{{ hostname_hostname_short }}{% endif %}{% endif %}"
    line: "127.0.1.1{{'\t'}}{% if hostname_hostname_loopback is defined %}{{'\t'}}{{ hostname_hostname_loopback }}{% endif %}"
    state: present
  become: yes
