---
# This playbook contains common plays that will be run on all nodes.

- name: Assert platform is supported
  tags: hostname
  assert:
    that:
      - ansible_os_family in ['Archlinux', 'Debian', 'RedHat', 'CentOS', 'Suse', 'Linuxmint']
      - ansible_architecture in ['x86_64']

- import_tasks: hostname.yml
  when: (ansible_os_family not in ['Darwin'])
  tags: [hostname]

