---
# Handler to handle common notifications. Handlers are called by other plays.
# See http://ansible.cc/docs/playbooks.html for more information about handlers.

- name: restart NetworkManager
  systemd:
    state: restarted
    daemon_reload: true
    name: NetworkManager
  become: true
