---
dependency:
  name: galaxy
  enabled: true
  options:
    ignore-errors: true
driver:
  name: delegated
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: centos_7_hostname
    image: centos/systemd
    privileged: true
    command: /usr/sbin/init
  - name: ubuntu_16_04_hostname
    image: ubuntu:16.04
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # 2 below will be hard to get 100% right
    # - idempotence
    # - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
